-- Migration 059: sessions.enabled_plugins_json default '[]' → NULL (inherit).
--
-- INTENTIONALLY INERT. This numbered slot documents the schema change and bumps the
-- binary's schema-capability version (computeAppMaxMigrationVersion → user_version),
-- but performs NO SQL. The actual column rebuild is done by the shape-guarded
-- reconciler reconcileSessionsPluginsColumn (main/src/database/reconcileSessionsPluginsColumn.ts),
-- invoked from Database.reconcileSessionsSchema() after the file migrations run.
--
-- WHY NOT A NORMAL FILE MIGRATION:
-- Migration 039 declared `enabled_plugins_json TEXT NOT NULL DEFAULT '[]'`, which made
-- the NULL/inherit sentinel unreachable — every untouched session stored '[]' and, via
-- buildExclusiveEnabledPluginsMap, force-disabled ALL file-enabled plugins (e.g. codex)
-- at the flag precedence tier. The fix flips the default to NULL and backfills legacy
-- '[]' → NULL. That backfill is value-keyed (NULLIF(x,'[]')): expressed as an
-- ADD/DROP/RENAME swap in a .sql file it is NOT re-run-safe — the temp column is renamed
-- away, so a re-run (migration marker lost/reset) would NOT trip the runner's
-- "duplicate column name" idempotency signal and would silently re-convert a DELIBERATE
-- post-fix '[]' (disable-all) back to inherit. The reconciler guards on the column's
-- current shape (rebuild only while still NOT NULL), so it is idempotent regardless of
-- any marker and never re-touches a deliberate '[]'.
