/**
 * Reviewed subset of the Codex app-server protocol generated by Codex CLI
 * 0.143.0. Keep this file version-pinned until generated bindings replace it.
 */

export type AppServerRequestId = string | number;

export type AppServerJsonValue =
  | string
  | number
  | boolean
  | null
  | AppServerJsonValue[]
  | { [key: string]: AppServerJsonValue };

export interface AppServerRpcErrorObject {
  code: number;
  message: string;
  data?: AppServerJsonValue;
}

export interface AppServerClientInfo {
  name: string;
  title: string | null;
  version: string;
}

export interface AppServerInitializeCapabilities {
  experimentalApi: boolean;
  requestAttestation: boolean;
  mcpServerOpenaiFormElicitation?: boolean;
  optOutNotificationMethods?: string[] | null;
}

export interface AppServerInitializeParams {
  clientInfo: AppServerClientInfo;
  capabilities: AppServerInitializeCapabilities | null;
}

export interface AppServerInitializeResponse {
  userAgent: string;
  codexHome: string;
  platformFamily: string;
  platformOs: string;
}

export type CommandAction =
  | { type: 'read'; command: string; name: string; path: string }
  | { type: 'listFiles'; command: string; path: string | null }
  | { type: 'search'; command: string; query: string | null; path: string | null }
  | { type: 'unknown'; command: string };

export type FileSystemSpecialPath =
  | { kind: 'root' }
  | { kind: 'minimal' }
  | { kind: 'project_roots'; subpath: string | null }
  | { kind: 'tmpdir' }
  | { kind: 'slash_tmp' }
  | { kind: 'unknown'; path: string; subpath: string | null };

export type FileSystemPath =
  | { type: 'path'; path: string }
  | { type: 'glob_pattern'; pattern: string }
  | { type: 'special'; value: FileSystemSpecialPath };

export interface FileSystemSandboxEntry {
  path: FileSystemPath;
  access: 'read' | 'write' | 'deny';
}

export interface AdditionalFileSystemPermissions {
  read: string[] | null;
  write: string[] | null;
  globScanMaxDepth?: number;
  entries?: FileSystemSandboxEntry[];
}

export interface AdditionalPermissionProfile {
  network: { enabled: boolean | null } | null;
  fileSystem: AdditionalFileSystemPermissions | null;
}

export type NetworkApprovalProtocol = 'http' | 'https' | 'socks5Tcp' | 'socks5Udp';

export interface NetworkApprovalContext {
  host: string;
  protocol: NetworkApprovalProtocol;
}

export interface NetworkPolicyAmendment {
  host: string;
  action: 'allow' | 'deny';
}

export type ExecPolicyAmendment = string[];

export type CommandExecutionApprovalDecision =
  | 'accept'
  | 'acceptForSession'
  | { acceptWithExecpolicyAmendment: { execpolicy_amendment: ExecPolicyAmendment } }
  | { applyNetworkPolicyAmendment: { network_policy_amendment: NetworkPolicyAmendment } }
  | 'decline'
  | 'cancel';

export interface CommandExecutionRequestApprovalParams {
  threadId: string;
  turnId: string;
  itemId: string;
  startedAtMs: number;
  approvalId?: string | null;
  environmentId: string | null;
  reason?: string | null;
  networkApprovalContext?: NetworkApprovalContext | null;
  command?: string | null;
  cwd?: string | null;
  commandActions?: CommandAction[] | null;
  additionalPermissions?: AdditionalPermissionProfile | null;
  proposedExecpolicyAmendment?: ExecPolicyAmendment | null;
  proposedNetworkPolicyAmendments?: NetworkPolicyAmendment[] | null;
  availableDecisions?: CommandExecutionApprovalDecision[] | null;
}

export interface CommandExecutionRequestApprovalResponse {
  decision: CommandExecutionApprovalDecision;
}

export type FileChangeApprovalDecision =
  | 'accept'
  | 'acceptForSession'
  | 'decline'
  | 'cancel';

export interface FileChangeRequestApprovalParams {
  threadId: string;
  turnId: string;
  itemId: string;
  startedAtMs: number;
  reason?: string | null;
  grantRoot?: string | null;
}

export interface FileChangeRequestApprovalResponse {
  decision: FileChangeApprovalDecision;
}

interface McpElicitationSchemaBase {
  title?: string;
  description?: string;
}

export type McpElicitationPrimitiveSchema =
  | (McpElicitationSchemaBase & {
      type: 'string';
      minLength?: number;
      maxLength?: number;
      format?: 'email' | 'uri' | 'date' | 'date-time';
      default?: string;
    })
  | (McpElicitationSchemaBase & {
      type: 'number' | 'integer';
      minimum?: number;
      maximum?: number;
      default?: number;
    })
  | (McpElicitationSchemaBase & { type: 'boolean'; default?: boolean })
  | (McpElicitationSchemaBase & {
      type: 'string';
      enum: string[];
      enumNames?: string[];
      default?: string;
    })
  | (McpElicitationSchemaBase & {
      type: 'string';
      oneOf: Array<{ const: string; title: string }>;
      default?: string;
    })
  | (McpElicitationSchemaBase & {
      type: 'array';
      minItems?: number;
      maxItems?: number;
      items:
        | { type: 'string'; enum: string[] }
        | { anyOf: Array<{ const: string; title: string }> };
      default?: string[];
    });

export interface McpElicitationSchema {
  $schema?: string;
  type: 'object';
  properties: Record<string, McpElicitationPrimitiveSchema>;
  required?: string[];
}

interface McpServerElicitationRequestBase {
  threadId: string;
  turnId: string | null;
  serverName: string;
  _meta: AppServerJsonValue | null;
  message: string;
}

export type McpServerElicitationRequestParams =
  | (McpServerElicitationRequestBase & {
      mode: 'form';
      requestedSchema: McpElicitationSchema;
    })
  | (McpServerElicitationRequestBase & {
      mode: 'openai/form';
      requestedSchema: AppServerJsonValue;
    })
  | (McpServerElicitationRequestBase & {
      mode: 'url';
      url: string;
      elicitationId: string;
    });

export type McpServerElicitationAction = 'accept' | 'decline' | 'cancel';

export interface McpServerElicitationRequestResponse {
  action: McpServerElicitationAction;
  content: AppServerJsonValue | null;
  _meta: AppServerJsonValue | null;
}

export type AppServerServerRequest =
  | {
      method: 'item/commandExecution/requestApproval';
      id: AppServerRequestId;
      params: CommandExecutionRequestApprovalParams;
    }
  | {
      method: 'item/fileChange/requestApproval';
      id: AppServerRequestId;
      params: FileChangeRequestApprovalParams;
    }
  | {
      method: 'mcpServer/elicitation/request';
      id: AppServerRequestId;
      params: McpServerElicitationRequestParams;
    };

export type AppServerServerRequestMethod = AppServerServerRequest['method'];

export type AppServerServerResponseFor<M extends AppServerServerRequestMethod> =
  M extends 'item/commandExecution/requestApproval'
    ? CommandExecutionRequestApprovalResponse
    : M extends 'item/fileChange/requestApproval'
      ? FileChangeRequestApprovalResponse
      : McpServerElicitationRequestResponse;

