/**
 * Reviewed subset of the Codex app-server protocol generated by Codex CLI
 * 0.143.0. Keep this file version-pinned until generated bindings replace it.
 */

export type AppServerRequestId = string | number;

export type AppServerJsonValue =
  | string
  | number
  | boolean
  | null
  | AppServerJsonValue[]
  | { [key: string]: AppServerJsonValue };

export interface AppServerRpcErrorObject {
  code: number;
  message: string;
  data?: AppServerJsonValue;
}

export interface AppServerClientInfo {
  name: string;
  title: string | null;
  version: string;
}

export interface AppServerInitializeCapabilities {
  experimentalApi: boolean;
  requestAttestation: boolean;
  mcpServerOpenaiFormElicitation?: boolean;
  optOutNotificationMethods?: string[] | null;
}

export interface AppServerInitializeParams {
  clientInfo: AppServerClientInfo;
  capabilities: AppServerInitializeCapabilities | null;
}

export interface AppServerInitializeResponse {
  userAgent: string;
  codexHome: string;
  platformFamily: string;
  platformOs: string;
}

export type AppServerApprovalPolicy =
  | 'untrusted'
  | 'on-request'
  | {
      granular: {
        sandbox_approval: boolean;
        rules: boolean;
        skill_approval: boolean;
        request_permissions: boolean;
        mcp_elicitations: boolean;
      };
    }
  | 'never';

export type AppServerApprovalsReviewer = 'user' | 'auto_review' | 'guardian_subagent';

export type AppServerSandboxMode = 'read-only' | 'workspace-write' | 'danger-full-access';

interface AppServerThreadConfigurationParams {
  model?: string | null;
  cwd?: string | null;
  approvalPolicy?: AppServerApprovalPolicy | null;
  approvalsReviewer?: AppServerApprovalsReviewer | null;
  permissions?: string | null;
  config?: Record<string, AppServerJsonValue> | null;
  baseInstructions?: string | null;
  developerInstructions?: string | null;
}

export interface AppServerThreadStartParams extends AppServerThreadConfigurationParams {
  sandbox?: AppServerSandboxMode | null;
  ephemeral?: boolean | null;
  experimentalRawEvents?: boolean;
}

export interface AppServerThreadResumeParams extends AppServerThreadConfigurationParams {
  threadId: string;
  sandbox?: AppServerSandboxMode | null;
  excludeTurns?: boolean;
}

export interface AppServerThreadResponse {
  thread: {
    id: string;
  };
}

export type AppServerThreadStartResponse = AppServerThreadResponse;
export type AppServerThreadResumeResponse = AppServerThreadResponse;

export type AppServerImageDetail = 'auto' | 'low' | 'high' | 'original';

export type AppServerUserInput =
  | { type: 'text'; text: string; text_elements: AppServerJsonValue[] }
  | { type: 'image'; url: string; detail?: AppServerImageDetail }
  | { type: 'localImage'; path: string; detail?: AppServerImageDetail }
  | { type: 'skill'; name: string; path: string }
  | { type: 'mention'; name: string; path: string };

export interface AppServerTurnStartParams {
  threadId: string;
  input: AppServerUserInput[];
  cwd?: string | null;
  approvalPolicy?: AppServerApprovalPolicy | null;
  approvalsReviewer?: AppServerApprovalsReviewer | null;
  sandboxPolicy?: AppServerJsonValue | null;
  permissions?: string | null;
  model?: string | null;
  effort?: string | null;
  outputSchema?: AppServerJsonValue | null;
}

export interface AppServerTurnStartResponse {
  turn: {
    id: string;
  };
}

export interface AppServerTurnInterruptParams {
  threadId: string;
  turnId: string;
}

export type AppServerTurnInterruptResponse = Record<string, never>;

export interface TokenUsageBreakdown {
  totalTokens: number;
  inputTokens: number;
  cachedInputTokens: number;
  outputTokens: number;
  reasoningOutputTokens: number;
}

export interface ThreadTokenUsage {
  total: TokenUsageBreakdown;
  last: TokenUsageBreakdown;
  modelContextWindow: number | null;
}

export interface ThreadTokenUsageUpdatedNotification {
  threadId: string;
  turnId: string;
  tokenUsage: ThreadTokenUsage;
}

export type CommandAction =
  | { type: 'read'; command: string; name: string; path: string }
  | { type: 'listFiles'; command: string; path: string | null }
  | { type: 'search'; command: string; query: string | null; path: string | null }
  | { type: 'unknown'; command: string };

export type FileSystemSpecialPath =
  | { kind: 'root' }
  | { kind: 'minimal' }
  | { kind: 'project_roots'; subpath: string | null }
  | { kind: 'tmpdir' }
  | { kind: 'slash_tmp' }
  | { kind: 'unknown'; path: string; subpath: string | null };

export type FileSystemPath =
  | { type: 'path'; path: string }
  | { type: 'glob_pattern'; pattern: string }
  | { type: 'special'; value: FileSystemSpecialPath };

export interface FileSystemSandboxEntry {
  path: FileSystemPath;
  access: 'read' | 'write' | 'deny';
}

export interface AdditionalFileSystemPermissions {
  read: string[] | null;
  write: string[] | null;
  globScanMaxDepth?: number;
  entries?: FileSystemSandboxEntry[];
}

export interface AdditionalPermissionProfile {
  network: { enabled: boolean | null } | null;
  fileSystem: AdditionalFileSystemPermissions | null;
}

export type NetworkApprovalProtocol = 'http' | 'https' | 'socks5Tcp' | 'socks5Udp';

export interface NetworkApprovalContext {
  host: string;
  protocol: NetworkApprovalProtocol;
}

export interface NetworkPolicyAmendment {
  host: string;
  action: 'allow' | 'deny';
}

export type ExecPolicyAmendment = string[];

export type CommandExecutionApprovalDecision =
  | 'accept'
  | 'acceptForSession'
  | { acceptWithExecpolicyAmendment: { execpolicy_amendment: ExecPolicyAmendment } }
  | { applyNetworkPolicyAmendment: { network_policy_amendment: NetworkPolicyAmendment } }
  | 'decline'
  | 'cancel';

export interface CommandExecutionRequestApprovalParams {
  threadId: string;
  turnId: string;
  itemId: string;
  startedAtMs: number;
  approvalId?: string | null;
  environmentId: string | null;
  reason?: string | null;
  networkApprovalContext?: NetworkApprovalContext | null;
  command?: string | null;
  cwd?: string | null;
  commandActions?: CommandAction[] | null;
  additionalPermissions?: AdditionalPermissionProfile | null;
  proposedExecpolicyAmendment?: ExecPolicyAmendment | null;
  proposedNetworkPolicyAmendments?: NetworkPolicyAmendment[] | null;
  availableDecisions?: CommandExecutionApprovalDecision[] | null;
}

export interface CommandExecutionRequestApprovalResponse {
  decision: CommandExecutionApprovalDecision;
}

export type FileChangeApprovalDecision =
  | 'accept'
  | 'acceptForSession'
  | 'decline'
  | 'cancel';

export interface FileChangeRequestApprovalParams {
  threadId: string;
  turnId: string;
  itemId: string;
  startedAtMs: number;
  reason?: string | null;
  grantRoot?: string | null;
}

export interface FileChangeRequestApprovalResponse {
  decision: FileChangeApprovalDecision;
}

export interface ToolRequestUserInputOption {
  label: string;
  description: string;
}

export interface ToolRequestUserInputQuestion {
  id: string;
  header: string;
  question: string;
  isOther: boolean;
  isSecret: boolean;
  options: ToolRequestUserInputOption[] | null;
}

export interface ToolRequestUserInputParams {
  threadId: string;
  turnId: string;
  itemId: string;
  questions: ToolRequestUserInputQuestion[];
  autoResolutionMs: number | null;
}

export interface ToolRequestUserInputResponse {
  answers: Record<string, { answers: string[] }>;
}

export interface PermissionsRequestApprovalParams {
  threadId: string;
  turnId: string;
  itemId: string;
  environmentId: string | null;
  startedAtMs: number;
  cwd: string;
  reason: string | null;
  permissions: AdditionalPermissionProfile;
}

export interface GrantedPermissionProfile {
  network?: { enabled: boolean | null };
  fileSystem?: AdditionalFileSystemPermissions;
}

export interface PermissionsRequestApprovalResponse {
  permissions: GrantedPermissionProfile;
  scope: 'turn' | 'session';
  strictAutoReview?: boolean;
}

interface McpElicitationSchemaBase {
  title?: string;
  description?: string;
}

export type McpElicitationPrimitiveSchema =
  | (McpElicitationSchemaBase & {
      type: 'string';
      minLength?: number;
      maxLength?: number;
      format?: 'email' | 'uri' | 'date' | 'date-time';
      default?: string;
    })
  | (McpElicitationSchemaBase & {
      type: 'number' | 'integer';
      minimum?: number;
      maximum?: number;
      default?: number;
    })
  | (McpElicitationSchemaBase & { type: 'boolean'; default?: boolean })
  | (McpElicitationSchemaBase & {
      type: 'string';
      enum: string[];
      enumNames?: string[];
      default?: string;
    })
  | (McpElicitationSchemaBase & {
      type: 'string';
      oneOf: Array<{ const: string; title: string }>;
      default?: string;
    })
  | (McpElicitationSchemaBase & {
      type: 'array';
      minItems?: number;
      maxItems?: number;
      items:
        | { type: 'string'; enum: string[] }
        | { anyOf: Array<{ const: string; title: string }> };
      default?: string[];
    });

export interface McpElicitationSchema {
  $schema?: string;
  type: 'object';
  properties: Record<string, McpElicitationPrimitiveSchema>;
  required?: string[];
}

interface McpServerElicitationRequestBase {
  threadId: string;
  turnId: string | null;
  serverName: string;
  _meta: AppServerJsonValue | null;
  message: string;
}

export type McpServerElicitationRequestParams =
  | (McpServerElicitationRequestBase & {
      mode: 'form';
      requestedSchema: McpElicitationSchema;
    })
  | (McpServerElicitationRequestBase & {
      mode: 'openai/form';
      requestedSchema: AppServerJsonValue;
    })
  | (McpServerElicitationRequestBase & {
      mode: 'url';
      url: string;
      elicitationId: string;
    });

export type McpServerElicitationAction = 'accept' | 'decline' | 'cancel';

export interface McpServerElicitationRequestResponse {
  action: McpServerElicitationAction;
  content: AppServerJsonValue | null;
  _meta: AppServerJsonValue | null;
}

export type AppServerServerRequest =
  | {
      method: 'item/commandExecution/requestApproval';
      id: AppServerRequestId;
      params: CommandExecutionRequestApprovalParams;
    }
  | {
      method: 'item/fileChange/requestApproval';
      id: AppServerRequestId;
      params: FileChangeRequestApprovalParams;
    }
  | {
      method: 'item/tool/requestUserInput';
      id: AppServerRequestId;
      params: ToolRequestUserInputParams;
    }
  | {
      method: 'item/permissions/requestApproval';
      id: AppServerRequestId;
      params: PermissionsRequestApprovalParams;
    }
  | {
      method: 'mcpServer/elicitation/request';
      id: AppServerRequestId;
      params: McpServerElicitationRequestParams;
    };

export type AppServerServerRequestMethod = AppServerServerRequest['method'];

export type AppServerServerResponseFor<M extends AppServerServerRequestMethod> =
  M extends 'item/commandExecution/requestApproval'
    ? CommandExecutionRequestApprovalResponse
    : M extends 'item/fileChange/requestApproval'
      ? FileChangeRequestApprovalResponse
      : M extends 'item/tool/requestUserInput'
        ? ToolRequestUserInputResponse
        : M extends 'item/permissions/requestApproval'
          ? PermissionsRequestApprovalResponse
          : McpServerElicitationRequestResponse;
